(define/contract (area-of-max-diagonal dimensions)
  (-> (listof (listof exact-integer?)) exact-integer?)
  (define-values (best-diag best-area)
    (for/fold ([bd 0] [ba 0]) ([d dimensions])
      (define l (first d))
      (define w (second d))
      (define diag (+ (* l l) (* w w)))
      (define area (* l w))
      (if (or (> diag bd) (and (= diag bd) (> area ba)))
          (values diag area)
          (values bd ba))))
  best-area)
